jobs:
  build:
    docker:
      - image: cimg/node:16.6.2
    steps:
      - checkout
      - run: node --version
  node/test:
    version: '16.6.2'
    docker:
      - image: cimg/node:16.6.2
    steps:
      - checkout
      - run: yarn run test
