name: Run Tests

on:
  push:
    branches: [main, dependencies, develop]
  pull_request:
    branches: [main, dependencies, develop]
permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: ['javascript']
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

      - if: github.ref == 'ref/head/master' || github.ref == 'ref/head/develop'
        name: yarn install and update snapshot
        run: |
          yarn install --frozen-lockfile
          yarn run test:unit

      - if: "!(github.ref == 'ref/head/master' || github.ref == 'ref/head/develop')"
        name: npm install and test
        run: |
          yarn install --frozen-lockfile
          yarn run test:unit:ci

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          exitOnceUploaded: true

      - if: ${{ github.actor == 'dependabot[bot]' }}
        name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
