name: Test
'on':
  push: null
  pull_request: null
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - if: github.ref == 'ref/head/master' || github.ref == 'ref/head/develop'
        name: yarn install and update snapshot
        run: |
          yarn install --frozen-lockfile
          yarn run test:unit
      - if: '!(github.ref == ''ref/head/master'' || github.ref == ''ref/head/develop'')'
        name: npm install and test
        run: |
          yarn install --frozen-lockfile
          yarn run test:unit:ci
  full:
    name: Node.js 17 Full
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
        env:
          FORCE_COLOR: 2
  short:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18
          - 16
    name: Node.js ${{ matrix.node-version }} Quick
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run unit tests
        run: npx jest
        env:
          FORCE_COLOR: 2
